# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-01-09 23:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picshare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='category',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='picshare.Category'),
        ),
        migrations.AddField(
            model_name='images',
            name='image',
            field=models.ImageField(default='image.jpeg', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='images',
            name='location',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, to='picshare.Location'),
        ),
    ]
